export enum CMD {
  'RETRIEVE_BOOK_LIST' = 'CMD:RETRIEVE_BOOK_LIST',
  'RETRIEVE_BOOK' = 'CMD:RETRIEVE_BOOK',
  'RETRIEVE_SEARCHED_BOOK' = 'CMD:RETRIEVE_SEARCHED_BOOK',
  'RETRIEVE_FILTERED_BOOK' = 'CMD:RETRIEVE_FILTERED_BOOK',
  'UPDATE_BOOK' = 'CMD:UPDATE_BOOK',
  'DELETE_BOOK' = 'CMD:DELETE_BOOK',
  'CREATE_BOOK' = 'CMD:CREATE_BOOK',
}
